services:
  redis:
    image: redis:7.2-alpine
    ports: ["6379:6379"]
    command: ["redis-server","--save","","--appendonly","no"]

  api:
    build:
      context: .                                # <- repo root
      dockerfile: Howazit.Responses.Api/Dockerfile
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      DOTNET_ENVIRONMENT: Development
      REDIS__CONNECTIONSTRING: redis:6379
      SQLITE__CONNECTIONSTRING: Data Source=/app/data/howazit.db
    ports: ["8080:8080"]
    depends_on: ["redis"]
    volumes:
      - howazit_api_data:/app/data

volumes:
  howazit_api_data:
