services:
  redis:
    image: redis:7
    command: ["redis-server","--appendonly","yes","--requirepass","redispass"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redispass", "PING"]
      interval: 2s
      timeout: 1s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Howazit.Responses.Api/Dockerfile
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      DOTNET_ENVIRONMENT: Development
      REDIS__CONNECTIONSTRING: redis:6379,password=redispass,abortConnect=false
      SQLITE__CONNECTIONSTRING: Data Source=/app/data/howazit.db
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      ENCRYPT__PURPOSE: "howazit:v2:pii"
      ENCRYPT__PREVIOUS_PURPOSES: "howazit:v1:pii"
      ENCRYPT__USERAGENT: "true"
      DATAPROTECTION__KEYRING_PATH: "/app/data/dp-keys"
    ports: ["8080:8080"]
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - howazit_api_data:/app/data

volumes:
  howazit_api_data:
